### ISSUE TITLE
Robot Stabilization

### ISSUE THREAD

**Issue by AranBSmith** [resibots/hexapod_simu#22]
https://github.com/resibots/hexapod_simu/blob/7ca5da50a912ca90eab13bace991857e89955280/hexapod_dart/include/hexapod_dart/hexapod_dart_simu.hpp#L88

Hi, I was reading into the above line, and was wondering 
1. For the purpose of running this code in an EA in sferes2, how could this be avoided? How could it be avoided such that time might be saved when evolving individuals.
2. What would happen if the robot could not be stabilized, and what might be a good remedy?

**Comment by costashatz** [comment]
> 1. For the purpose of running this code in an EA in sferes2, how could this be avoided? How could it be avoided such that time might be saved when evolving individuals.

This code can be avoided by saving the state of the robot after a stabilization and then loaded before a new run. I didn't do this because at the moment, the load/save function in DART was not functioning properly. Now, from the DART side everything is okay, but this code is a bit deprecated. We are now using [robot_dart](https://github.com/resibots/robot_dart) which allows for more flexibility (and up to date with DART's latest master branch).

> 2\. What would happen if the robot could not be stabilized, and what might be a good remedy?

The way the code is structured, the robot will always stabilize and achieve the exact same state after stabilization. If you are asking more generally, this is really an open question..

**Comment by AranBSmith** [comment]
Perfect, thanks!
